### ISSUE TITLE
doc: "64 bit executables cannot be emulated on a 32 bit architecture and vice versa."

### ISSUE THREAD

**Issue by cedric-vincent** [polysquare/polysquare-travis-container#14]
Hello Sam,

You wrote "64 bit executables cannot be emulated on a 32 bit architecture and *vice versa*." in the documentation, however there's no problem to emulate 32-bit arch. on 64-bit systems (I do this most of the time).  I think the "vice versa" part is just a thinko :)

By the way I really like your project and I will advertise it to my coworkers.

Regards,
Cédric.

**Comment by smspillaz** [comment]
@cedric-vincent Ah thanks. I had assumed it didn't work the other way around too. I'll update the documentation. Thanks for the praise :) I hope this is useful. I'm using it to test some of my C++ projects on multiple distributions and architectures.
